// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFXdH4lfikpjS-lvzwG2mVeuIMxWp3gIo',
    appId: '1:280234817627:web:de45a1a29144611a5de77e',
    messagingSenderId: '280234817627',
    projectId: 'instagram-797d5',
    authDomain: 'instagram-797d5.firebaseapp.com',
    storageBucket: 'instagram-797d5.appspot.com',
    measurementId: 'G-MKZRGPEB9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmI-fFTYujm17YAr6cOMwmF6stMgs9EJk',
    appId: '1:280234817627:android:1a5599c04c64540d5de77e',
    messagingSenderId: '280234817627',
    projectId: 'instagram-797d5',
    storageBucket: 'instagram-797d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbEQtgPQB_sHunX4Npc75xSQn-rEs7KGs',
    appId: '1:280234817627:ios:9f0d7e18749e9e185de77e',
    messagingSenderId: '280234817627',
    projectId: 'instagram-797d5',
    storageBucket: 'instagram-797d5.appspot.com',
    iosClientId: '280234817627-5qo8k7up9eovev5n2v1rnvnh80l9eb98.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbEQtgPQB_sHunX4Npc75xSQn-rEs7KGs',
    appId: '1:280234817627:ios:ad72530d3f75126d5de77e',
    messagingSenderId: '280234817627',
    projectId: 'instagram-797d5',
    storageBucket: 'instagram-797d5.appspot.com',
    iosClientId: '280234817627-c9guh1c10t43u487oec883lgqamj3mfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapi.RunnerTests',
  );
}
